/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph */
        get: operations["graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph.gexf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph Gexf
         * @description Full graph in GEXF for Gephi desktop (File > Open).
         */
        get: operations["graph_gexf_api_graph_gexf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diseases/{disease_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disease */
        get: operations["disease_api_diseases__disease_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diseases/{disease_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Related */
        get: operations["related_api_diseases__disease_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diseases/{disease_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disease Graph */
        get: operations["disease_graph_api_diseases__disease_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diseases/{disease_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_diseases__disease_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diseases/{disease_id}/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opportunities */
        get: operations["opportunities_api_diseases__disease_id__opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{source_id}/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connection */
        get: operations["connection_api_connections__source_id___target_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/edges/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Edge */
        get: operations["edge_api_edges__edge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/edges/{edge_id}/judge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Judge */
        get: operations["judge_api_edges__edge_id__judge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evals */
        get: operations["evals_api_evals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/question-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Question Packs */
        get: operations["question_packs_api_question_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve
         * @description Resolve a query string to entities of any type, with synonym matching
         *     and hierarchy context.
         */
        get: operations["resolve_v1_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{curie}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch */
        get: operations["fetch_v1_entities__curie__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Traverse
         * @description The workhorse: any edge query, filterable by endpoint, channel,
         *     provenance, and judged confidence.
         */
        get: operations["traverse_v1_edges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Path
         * @description Why-connected for any node pair (not just diseases).
         */
        get: operations["path_v1_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/judge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Judge
         * @description Judge an arbitrary state with a question pack.
         *
         *     Requires the serving process to have Laya available (EMMATICS_JUDGE=laya).
         *     Without it, returns 501 so clients can degrade gracefully; stored edge
         *     judgments are unaffected (they are precomputed into the graph).
         */
        post: operations["judge_v1_judge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evals */
        get: operations["evals_v1_evals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConnectionExplanation */
        ConnectionExplanation: {
            source: components["schemas"]["Node"];
            target: components["schemas"]["Node"];
            /** Path */
            path: components["schemas"]["PathStep"][];
            /** Known */
            known: string[];
            /** Inferred */
            inferred: string[];
            /** Uncertain */
            uncertain: string[];
            /** Narrative */
            narrative: string;
            /** Evidence Edges */
            evidence_edges: components["schemas"]["Edge"][];
        };
        /** DecisionMeta */
        DecisionMeta: {
            /** Model */
            model: string;
            /** Question Pack */
            question_pack: string;
            /** Judged At */
            judged_at: string;
        };
        /** DiseaseDetail */
        DiseaseDetail: {
            disease: components["schemas"]["Node"];
            /** Genes */
            genes: components["schemas"]["Node"][];
            /** Variants */
            variants: components["schemas"]["Node"][];
            /** Phenotypes */
            phenotypes: components["schemas"]["Node"][];
            /** Mechanisms */
            mechanisms: components["schemas"]["Node"][];
            /** Pathways */
            pathways: components["schemas"]["Node"][];
            /** Publications */
            publications: components["schemas"]["Node"][];
            /** Studies */
            studies: components["schemas"]["Node"][];
            /** Researchers */
            researchers: components["schemas"]["Node"][];
            /** Organizations */
            organizations: components["schemas"]["Node"][];
            /** Assets */
            assets: components["schemas"]["Node"][];
        };
        /** Edge */
        Edge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Rel Type
             * @enum {string}
             */
            rel_type: "CAUSED_BY" | "HAS_VARIANT" | "HAS_PHENOTYPE" | "AFFECTS_PATHWAY" | "HAS_MECHANISM" | "STUDIED_IN" | "SUPPORTED_BY" | "AUTHORED_BY" | "HAS_ASSET" | "SHARES_MECHANISM" | "RELATED_TO" | "PHENOTYPE_SIMILAR" | "SHARES_GENE_MECHANISM" | "SUBTYPE_OF";
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "curated" | "inferred";
            /**
             * Description
             * @default
             */
            description: string;
            /** Source Db */
            source_db: string;
            /** Source Id */
            source_id: string;
            /**
             * Supporting Publications
             * @default []
             */
            supporting_publications: string[];
            /**
             * Contradictory Evidence
             * @default []
             */
            contradictory_evidence: string[];
            /** Rel Probs */
            rel_probs?: {
                [key: string]: number;
            } | null;
            evidence_level?: components["schemas"]["EvidenceLevel"] | null;
            /** Contradicted */
            contradicted?: number | null;
            /** Edge Valid */
            edge_valid?: number | null;
            /** State */
            state?: string | null;
            decision_meta?: components["schemas"]["DecisionMeta"] | null;
        };
        /** EdgesResponse */
        EdgesResponse: {
            /** Generation Id */
            generation_id: string;
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["Edge"][];
        };
        /** EntitiesResponse */
        EntitiesResponse: {
            /** Generation Id */
            generation_id: string;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["EntityHit"][];
        };
        /** EntityDetail */
        EntityDetail: {
            /** Generation Id */
            generation_id: string;
            node: components["schemas"]["Node"];
            /** Connections */
            connections: {
                [key: string]: number;
            };
            /** Parents */
            parents: components["schemas"]["Node"][];
            /** Subtypes */
            subtypes: components["schemas"]["Node"][];
        };
        /** EntityHit */
        EntityHit: {
            node: components["schemas"]["Node"];
            /** Match */
            match: string;
            /**
             * Parents
             * @default []
             */
            parents: components["schemas"]["Node"][];
            /**
             * Subtype Count
             * @default 0
             */
            subtype_count: number;
            /**
             * Connections
             * @default {}
             */
            connections: {
                [key: string]: number;
            };
        };
        /** EvalReport */
        EvalReport: {
            /** N */
            n: number;
            /** Accuracy */
            accuracy: number;
            /** Brier */
            brier: number;
            /** Ece */
            ece: number;
            /** Bins */
            bins: {
                [key: string]: unknown;
            }[];
            /** Notes */
            notes: string;
        };
        /**
         * EvidenceLevel
         * @description Distribution over an ordered evidence ladder (Laya `score` output).
         */
        EvidenceLevel: {
            /**
             * Expected
             * @description Expected level index, e.g. 2.3 = between replicated and clinical
             */
            expected: number;
            /** Probs */
            probs: {
                [key: string]: number;
            };
        };
        /** GraphPayload */
        GraphPayload: {
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Edges */
            edges: components["schemas"]["Edge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JudgeRequest */
        JudgeRequest: {
            /** State */
            state: string;
            /**
             * Pack Id
             * @default edge-validate-v1
             */
            pack_id: string;
        };
        /** Node */
        Node: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "Disease" | "Gene" | "Variant" | "Phenotype" | "Mechanism" | "Pathway" | "Publication" | "ClinicalTrial" | "Researcher" | "PatientOrganization" | "ResearchAsset";
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Identifier */
            identifier?: string | null;
            /** Inheritance */
            inheritance?: string | null;
            /** Year */
            year?: number | null;
            /** Status */
            status?: string | null;
            /** Affiliation */
            affiliation?: string | null;
            /** Asset Type */
            asset_type?: string | null;
            /** Synonyms */
            synonyms?: string[] | null;
        };
        /** Opportunity */
        Opportunity: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** What Exists */
            what_exists: string;
            /** Why Relevant */
            why_relevant: string;
            /** Evidence Edge Ids */
            evidence_edge_ids: string[];
            /** Needs Validation */
            needs_validation: string[];
            /** Next Step */
            next_step: string;
            /**
             * Disclaimer
             * @default Research opportunity requiring expert validation. Not a medical recommendation.
             */
            disclaimer: string;
        };
        /** PathResponse */
        PathResponse: {
            /** Generation Id */
            generation_id: string;
            /** Path */
            path: components["schemas"]["PathStep"][];
            /** Known */
            known: string[];
            /** Inferred */
            inferred: string[];
            /** Uncertain */
            uncertain: string[];
            /** Narrative */
            narrative: string;
            /** Evidence Edges */
            evidence_edges: components["schemas"]["Edge"][];
        };
        /** PathStep */
        PathStep: {
            node: components["schemas"]["Node"];
            edge?: components["schemas"]["Edge"] | null;
        };
        /** RelatedDisease */
        RelatedDisease: {
            disease: components["schemas"]["Node"];
            /** Similarity */
            similarity: number;
            /** Shared Phenotypes */
            shared_phenotypes: components["schemas"]["Node"][];
            /** Shared Pathways */
            shared_pathways: components["schemas"]["Node"][];
            /** Genes */
            genes: components["schemas"]["Node"][];
            connecting_edge: components["schemas"]["Edge"];
        };
        /** SearchResult */
        SearchResult: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "Disease" | "Gene" | "Variant" | "Phenotype" | "Mechanism" | "Pathway" | "Publication" | "ClinicalTrial" | "Researcher" | "PatientOrganization" | "ResearchAsset";
            /** Name */
            name: string;
            /** Identifier */
            identifier?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_api_search_get: {
        parameters: {
            query?: {
                /** @description query string */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_api_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPayload"];
                };
            };
        };
    };
    graph_gexf_api_graph_gexf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    disease_api_diseases__disease_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disease_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiseaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_api_diseases__disease_id__related_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disease_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedDisease"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disease_graph_api_diseases__disease_id__graph_get: {
        parameters: {
            query?: {
                depth?: number;
            };
            header?: never;
            path: {
                disease_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_diseases__disease_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disease_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edge"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opportunities_api_diseases__disease_id__opportunities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disease_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opportunity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connection_api_connections__source_id___target_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
                target_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionExplanation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edge_api_edges__edge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    judge_api_edges__edge_id__judge_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evals_api_evals_get: {
        parameters: {
            query?: {
                judge?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    question_packs_api_question_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    resolve_v1_entities_get: {
        parameters: {
            query: {
                q: string;
                /** @description comma-separated NodeTypes */
                types?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_v1_entities__curie__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curie: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traverse_v1_edges_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                /** @description match either endpoint */
                node?: string | null;
                /** @description comma-separated */
                rel_types?: string;
                provenance?: string | null;
                min_valid?: number | null;
                judged_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    path_v1_paths_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    judge_v1_judge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evals_v1_evals_get: {
        parameters: {
            query?: {
                judge?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
